### ISSUE TITLE
Help needed ? like to use machine function outside a plugin

### ISSUE THREAD

**Issue by dorel14** [DandyDev/slack-machine#332]
Hi 
I'll like to create a generic function to say soehing to slack
here is a piece of code
`# -*- coding: UTF-8 -*-
from plugins.helpers.gmail import Gmail
from machine.plugins.base import MachineBasePlugin

def mailToSlack(channel,
                labelsToSearch=[],
                labelsToRemove=[],
                labelsToAdd=[]):
    gm = Gmail()
    mb = MachineBasePlugin()
    reponse = gm.readMailExtranet(labelsToSearch,
                                  labelsToRemove,
                                  labelsToAdd)
    if reponse:
        print('reponse', reponse)
        mb.say(channel=channel,
               text=reponse)`

the purpose is to pick a specific label from gmail and post a message in slack
when i try this i have this message 
'TypeError: __init__() missing 3 required positional arguments: 'client', 'settings', and 'storage''

**Comment by seerickcode** [comment]
_Don't fight it - make a plugin._
The whole point of SM is to be a bot framework that reacts to user input or some other triggers.  This is done by creating plugins.

If you just need your program to send output to slack, just use [python-slackclient](https://github.com/slackapi/python-slackclient) instead of a bot.

MachineBasePlugin doesn't work in isolation, it's a base class for Plugins, and those plugins need to be created by the Slack Machine core code.   That code is what would be providing the 'client', 'settings' and 'storage' arguments.

If you need to run some action on a schedule, use @schedule.  Beyond that, it's hard to suggest other methods because I don't know when/what is calling mailToSlack with arguments, but I would think that code should also be in a plugin.

**Comment by DandyDev** [comment]
@seerickcode has the right of it. You're trying to use Slack Machine in a way that it is not supported, nor is it _meant_ to be used like this.

And @dorel14, if I can make a suggestion, please use
```
code blocks
```
for formatting your code examples. You're opening a lot of issues on here, which I appreciate, because it means Slack Machine is being used. But your issues are often hard to comprehend due to  bad formatting and unclear language.

Closing for now.
